package models

import (
	"fmt"

	"github.com/google/uuid"
)

// Card represents a tarot card with Portuguese meanings
type Card struct {
	ID           string `json:"id"`
	NamePT       string `json:"name_pt"`
	NameShort    string `json:"name_short"`
	Type         string `json:"type"` // "major" or "minor"
	Suit         string `json:"suit,omitempty"`
	ValueInt     int    `json:"value_int"`
	MeaningUpPT  string `json:"meaning_up_pt"`
	MeaningRevPT string `json:"meaning_rev_pt"`
	DescPT       string `json:"desc_pt,omitempty"`
	ImageURL     string `json:"image_url"`
	KeywordsUp   string `json:"keywords_up,omitempty"`   // Palavras-chave (sentido direto)
	KeywordsRev  string `json:"keywords_rev,omitempty"`   // Palavras-chave (sentido reverso)
	Astrology    string `json:"astrology,omitempty"`      // Astrologia associada
	Element      string `json:"element,omitempty"`        // Elemento (Água, Fogo, etc)
	Crystal      string `json:"crystal,omitempty"`        // Pedra associada
}

// DefaultCards returns all 74 Rider-Waite-Smith tarot cards (TaionWC deck) with pt-BR meanings
func DefaultCards() []Card {
	cards := []Card{
		// ===== ARCANOS MAIORES (Major Arcana) - 22 cards =====
		{
			ID:           "ar00",
			NamePT:       "O Louco",
			NameShort:    "ar00",
			Type:         "major",
			ValueInt:     0,
			MeaningUpPT:  "Novidade, inocência, início de jornada, espontaneidade, liberdade, potencial ilimitado, confiança na vida.",
			MeaningRevPT: "Ações impulsivas, risco excessivo, falta de responsabilidade, instabilidade, confusão.",
			DescPT:       "Um indivíduo com chapéu de cogumelo saltando de um penhasco com uma flor e uma bolsa. Início de jornada, confiança na vida.",
			KeywordsUp:   "Inocência, libertação, novidade, potencial, confiança, espontaneidade",
			KeywordsRev:  "Imprudência, desatenção, risco, instabilidade, falta de direção",
			Astrology:    "Plutão (transformação)",
			Element:      "Fogo",
			Crystal:      "Quartzo Claro",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar00.jpg",
		},
		{
			ID:           "ar01",
			NamePT:       "O Mago",
			NameShort:    "ar01",
			Type:         "major",
			ValueInt:     1,
			MeaningUpPT:  "Capacidade, iniciativa, vontade, recursos, energia vital, criação, poder pessoal, habilidades.",
			MeaningRevPT: "Destruição, manipulação, perigo, recursos mal utilizados, fraude, falsidade.",
			DescPT:       "Um mestre com ferramentas ao redor, um dedo apontando para o céu e outro para a terra. Capacidade de agir com recursos ilimitados.",
			KeywordsUp:   "Manifestação, poder, habilidade, comunicação, ação, criação, recursos",
			KeywordsRev:  "Manipulation, block, fraude, esforço frustrado, falta de foco, mentira",
			Astrology:    "Mercúrio (comunicação, mente)",
			Element:      "Ar",
			Crystal:      "Lapislázuli",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar01.jpg",
		},
		{
			ID:           "ar02",
			NamePT:       "A Sacerdotisa",
			NameShort:    "ar02",
			Type:         "major",
			ValueInt:     2,
			MeaningUpPT:  "Intuição, sabedoria interior, mistério, conhecimento oculto, espiritualidade, silêncio, introspecção.",
			MeaningRevPT: "Segredos, silêncio demais, esquecimento, lack de fé, opacidade, falta de clareza.",
			DescPT:       "Uma sacerdotisa entre dois pilaros, com um poto lunar e um livro. Intuição, sabedoria interior, mistério.",
			KeywordsUp:   "Intuição, sabedoria, mistério, subconsciente, medo, silêncio",
			KeywordsRev:  "Ocultação, segredo, falta de clareza, medo, bloqueio, negligência",
			Astrology:    "Lua (intuição, subconsciente)",
			Element:      "Água",
			Crystal:      "Quartzo Rosa",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar02.jpg",
		},
		{
			ID:           "ar03",
			NamePT:       "A Imperatriz",
			NameShort:    "ar03",
			Type:         "major",
			ValueInt:     3,
			MeaningUpPT:  "Fertilidade, abundância, natureza, crescimento, conforto, maternidade, prosperidade, beleza.",
			MeaningRevPT: "Criatividade bloqueada, dependência, excesso de conforto, preguiça, estagnação.",
			DescPT:       "Uma imperatriz sentada em um campo com um escudo e um corsário. Fertilidade, abundância, natureza, crescimento.",
			KeywordsUp:   "Fertilidade, abundância, crescimento, natureza, abundância, prosperidade, maternidade",
			KeywordsRev:  "Estagnação, dependência, bloqueio criativo, preguiça, excesso de conforto, materialismo",
			Astrology:    "Vênus (amor, beleza, abundância)",
			Element:      "Terra",
			Crystal:      "Esmeralda",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar03.jpg",
		},
		{
			ID:           "ar04",
			NamePT:       "O Imperador",
			NameShort:    "ar04",
			Type:         "major",
			ValueInt:     4,
			MeaningUpPT:  "Autoridade, poder, estabilidade, controle, governança, disciplina, responsabilidade, estrutura.",
			MeaningRevPT: "Tirania, controle excessivo, rigidez, abuso de poder, falta de adaptação, autoritarismo.",
			DescPT:       "Um imperador sentado em um trono de pedra com um cajado de bichos. Autoridade, poder, estabilidade, controle.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar04.jpg",
		},
		{
			ID:           "ar05",
			NamePT:       "O Hierofone",
			NameShort:    "ar05",
			Type:         "major",
			ValueInt:     5,
			MeaningUpPT:  "Conhecimento espiritual, fé, orientação, tradicional, psicologia, ensino, sabedoria divina, compromisso.",
			MeaningRevPT: "Dogma, ortodoxia rígida, ignorância, falta de fé, dúvida, ensino falso.",
			DescPT:       "Um sacerdote com chaves cruzadas, representando a fé. Conhecimento espiritual, fé, orientação.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar05.jpg",
		},
		{
			ID:           "ar06",
			NamePT:       "Os Amantes",
			NameShort:    "ar06",
			Type:         "major",
			ValueInt:     6,
			MeaningUpPT:  "Escolha, relacionamento, união, valores, paixão, harmonia, conexão, decisão importante.",
			MeaningRevPT: "Desunião, discordância, escolha errada, perda de valores, relacionamento tóxico.",
			DescPT:       "Um homem e uma mulher com anjos e árvore do conhecimento. Escolha, relacionamento, união, valores.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar06.jpg",
		},
		{
			ID:           "ar07",
			NamePT:       "O Carro",
			NameShort:    "ar07",
			Type:         "major",
			ValueInt:     7,
			MeaningUpPT:  "Vitória, vontade, determinação, sucesso, confiança, controle, motivação, superação de obstáculos.",
			MeaningRevPT: "Falta de controle, impulsividade, derrota, fracasso, desmotivação, confusão.",
			DescPT:       "Um cavaleiro em um carro dirigido por sirenas. Vitória, vontade, determinação, sucesso, confiança.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar07.jpg",
		},
		{
			ID:           "ar08",
			NamePT:       "A Força",
			NameShort:    "ar08",
			Type:         "major",
			ValueInt:     8,
			MeaningUpPT:  "Coragem, força interna, perseverança, fé, autocontrole, bravura, paciência, gentileza.",
			MeaningRevPT: "Insegurança, fraqueza, perda de controle, força bruta, agressividade, pavor.",
			DescPT:       "Uma mulher fechando a boca de um leão. Coragem, força interna, perseverança, fé.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar08.jpg",
		},
		{
			ID:           "ar09",
			NamePT:       "O Eremita",
			NameShort:    "ar09",
			Type:         "major",
			ValueInt:     9,
			MeaningUpPT:  "Sabedoria interior, introspecção, isolamento, solitude, reflexão, orientação espiritual, paciência.",
			MeaningRevPT: "Isolamento excessivo, solidão, falta de orientação, depressão, introspecção excessiva.",
			DescPT:       "Um eremita com uma lanterna, caminhando nas montanhas. Sabedoria interior, introspecção, isolamento.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar09.jpg",
		},
		{
			ID:           "ar10",
			NamePT:       "A Roda da Fortuna",
			NameShort:    "ar10",
			Type:         "major",
			ValueInt:     10,
			MeaningUpPT:  "Mudança, sorte, destino, ciclos, transformação, virada de mesa, oportunidade, lição da vida.",
			MeaningRevPT: "Má sorte, obstáculos, reversão, fracasso, estagnação, resistência à mudança.",
			DescPT:       "Uma roda com símbolos de diferentes criaturas. Mudança, sorte, destino, ciclos, transformação.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar10.jpg",
		},
		{
			ID:           "ar11",
			NamePT:       "A Justiça",
			NameShort:    "ar11",
			Type:         "major",
			ValueInt:     11,
			MeaningUpPT:  "Equilíbrio, justiça, verdade, responsabilidade, causa e efeito, honestidade, legalidade.",
			MeaningRevPT: "Injustiça, prejuízo, culpa, indecisão, falta de responsabilidade, falsidade.",
			DescPT:       "Uma figura com uma balança e uma espada. Equilíbrio, justiça, verdade, responsabilidade.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar11.jpg",
		},
		{
			ID:           "ar12",
			NamePT:       "O Enforcado",
			NameShort:    "ar12",
			Type:         "major",
			ValueInt:     12,
			MeaningUpPT:  "Sacrifício, mudança de perspectiva, paciência, libertinagem, rendição, inversão, insight.",
			MeaningRevPT: "Medo, resistência, falta de adaptação, victimização, atadura, bloqueio.",
			DescPT:       "Um homem invertido em uma cruz, com um disco solar atrás. Sacrifício, mudança de perspectiva, paciência.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar12.jpg",
		},
		{
			ID:           "ar13",
			NamePT:       "A Morte",
			NameShort:    "ar13",
			Type:         "major",
			ValueInt:     13,
			MeaningUpPT:  "Transformação, fim de ciclos, renovação, mudança profunda, libertação, novos começos.",
			MeaningRevPT: "Necrose, estagnação, medo de mudança, resistência, fim sem renovação, obsolecimento.",
			DescPT:       "Um cavaleiro com um caveira e uma bandeira preta. Transformação, fim de ciclos, renovação.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar13.jpg",
		},
		{
			ID:           "ar14",
			NamePT:       "A Temperança",
			NameShort:    "ar14",
			Type:         "major",
			ValueInt:     14,
			MeaningUpPT:  "Equilíbrio, harmonia, paciência, moderação, adaptação, cura, unificação, flexibilidade.",
			MeaningRevPT: "Excesso, desequilíbrio, falta de paciência, rigidez, procupação, desadaptação.",
			DescPT:       "Um anjo misturando líquidos em duas taças. Equilíbrio, harmonia, paciência, moderação.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar14.jpg",
		},
		{
			ID:           "ar15",
			NamePT:       "O Diabo",
			NameShort:    "ar15",
			Type:         "major",
			ValueInt:     15,
			MeaningUpPT:  "Vício, limitação, materialismo, escravidão, tentação, dependência, sombra, desejos reprimidos.",
			MeaningRevPT: "Libertação, quebra de vícios, autonomia, desapego, amadurecimento, consciência.",
			DescPT:       "Um diabo com mulheres encadeadas. Vício, limitação, materialismo, escravidão, tentação.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar15.jpg",
		},
		{
			ID:           "ar16",
			NamePT:       "A Torre",
			NameShort:    "ar16",
			Type:         "major",
			ValueInt:     16,
			MeaningUpPT:  "Cole instability, mudança abrupta, destruição de ilusões, revelação, caos, libertação súbita.",
			MeaningRevPT: "Evitação de mudanças, proteção excessiva, medo de colapso, frustração, resistência alheia.",
			DescPT:       "Uma torre sendo atingida por relâmpago com pessoas caindo. Cole instability, mudança abrupta, destruição de ilusões.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar16.jpg",
		},
		{
			ID:           "ar17",
			NamePT:       "A Estrela",
			NameShort:    "ar17",
			Type:         "major",
			ValueInt:     17,
			MeaningUpPT:  "Esperança, inspiração, serenidade, fé, guia, clareza, regeneração, propósito divino.",
			MeaningRevPT: "Desespero, falta de fé, desalinhamento, confusão, perda de direção, cinismo.",
			DescPT:       "Uma mulher despejando água sob uma estrela. Esperança, inspiração, serenidade, fé.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar17.jpg",
		},
		{
			ID:           "ar18",
			NamePT:       "A Lua",
			NameShort:    "ar18",
			Type:         "major",
			ValueInt:     18,
			MeaningUpPT:  "Instinto, medo, ilusão, subconsciente, mistério, sonho, intuição, angústia.",
			MeaningRevPT: "Clareza, percepção, medo superado, realidade, ilusão quebrada, consciência.",
			DescPT:       "Uma lua com duas criaturas e um caminho entre água e cães. Instinto, medo, ilusão, subconsciente.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar18.jpg",
		},
		{
			ID:           "ar19",
			NamePT:       "O Sol",
			NameShort:    "ar19",
			Type:         "major",
			ValueInt:     19,
			MeaningUpPT:  "Alegria, sucesso, vitalidade, vida, confiança, realização, positividade, harmonia child.",
			MeaningRevPT: "Excesso de confiança, arrogância, perda de alegria, pessimismo, falta de vitalidade.",
			DescPT:       "Um sol brilhante com crianças e um cavalo. Alegria, sucesso, vitalidade, vida, confiança.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar19.jpg",
		},
		{
			ID:           "ar20",
			NamePT:       "O Juízo",
			NameShort:    "ar20",
			Type:         "major",
			ValueInt:     20,
			MeaningUpPT:  "Renovação, transformação, chamamento, avaliação, redenção, arrependimento, juízo final.",
			MeaningRevPT: "Negativa, falha, arrependimento, julgamento externo, procrastinação, dívida.",
			DescPT:       "Anjos tocando trombetas com cadáveres resurrectos. Renovação, transformação, chamamento.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar20.jpg",
		},
		{
			ID:           "ar21",
			NamePT:       "O Mundo",
			NameShort:    "ar21",
			Type:         "major",
			ValueInt:     21,
			MeaningUpPT:  "Conclusão, integração, realização, ciclo completo, successo, sabedoria, universo, realização pessoal.",
			MeaningRevPT: "Incompletude, falta de conclusão, fracasso, estagnação, falta de integração.",
			DescPT:       "Uma mulher com galho e serpente dentro de um ovillo. Conclusão, integração, realização, ciclo completo.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ar21.jpg",
		},
		// ===== ARCANOS MENORES (Minor Arcana) =====

		// ---- COPAS (Cups) - Emoções, relacionamentos, intuição ----
		{
			ID:           "cp01",
			NamePT:       "As de Copas",
			NameShort:    "cp01",
			Type:         "minor",
			Suit:         "cups",
			ValueInt:     1,
			MeaningUpPT:  "Novas emoções, amor, felicidade, oportunidade emocional, fertilidade, resposta positiva.",
			MeaningRevPT: "Emoções bloqueadas, amor negado, falta de entrega, frustração emocional, indiferença.",
			DescPT:       "Um copo comeado por uma mão celeste, com uma serpente e folhas. Novas emoções, amor, felicidade.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/cp01.jpg",
		},
		{
			ID:           "cp02",
			NamePT:       "Dois de Copas",
			NameShort:    "cp02",
			Type:         "minor",
			Suit:         "cups",
			ValueInt:     2,
			MeaningUpPT:  "União, conexão, relacionamento, parceria, escolha, harmonia, troca emocional.",
			MeaningRevPT: "Separação, disharmonia, indecisão, falta de conexão, relacionamento frágil.",
			DescPT:       "Um homem e uma mulher trocando copos, com um vaso e bovinos. União, conexão, relacionamento, parceria.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/cp02.jpg",
		},
		{
			ID:           "cp03",
			NamePT:       "Três de Copas",
			NameShort:    "cp03",
			Type:         "minor",
			Suit:         "cups",
			ValueInt:     3,
			MeaningUpPT:  "Celebração, amizade, alegria, realização, triunfo, união, orgulho, confiança.",
			MeaningRevPT: "Falta de alegria, celebração truncada, rivalidade, ciúme, sabotagem, melancolia.",
			DescPT:       "Três mulheres com copos, com um cachorro. Celebração, amizade, alegria, realização.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/cp03.jpg",
		},
		{
			ID:           "cp04",
			NamePT:       "Quatro de Copas",
			NameShort:    "cp04",
			Type:         "minor",
			Suit:         "cups",
			ValueInt:     4,
			MeaningUpPT:  "Conforto, satisfação, reflexão, paz, contentamento, ilusão, expectativa, meditação.",
			MeaningRevPT: "Boredom, falta de entusiasmo, insatisfação, estagnação, monotonia, autoindulgência.",
			DescPT:       "Um homem contemplando quatro copos, com um anjo. Conforto, satisfação, reflexão, paz.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/cp04.jpg",
		},
		{
			ID:           "cp05",
			NamePT:       "Cinco de Copas",
			NameShort:    "cp05",
			Type:         "minor",
			Suit:         "cups",
			ValueInt:     5,
			MeaningUpPT:  "Perda emocional, tristeza, luto, desespero, abandono, frustração, solidão.",
			MeaningRevPT: "Perda recuperada, mudança emocional, aceitação, recomposição, renovação do amor.",
			DescPT:       "Um homem de chapéu vendido olhando para dois copos cheios, com outros vazios. Perda emocional, tristeza, luto.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/cp05.jpg",
		},
		{
			ID:           "cp06",
			NamePT:       "Seis de Copas",
			NameShort:    "cp06",
			Type:         "minor",
			Suit:         "cups",
			ValueInt:     6,
			MeaningUpPT:  "Nostalgia, felicidade do passado, inocência, equilíbrio emocional, acolhimento, infância.",
			MeaningRevPT: "Nostalgia excessiva, sentimentalismo, idealização, regressão, infelicidade passada.",
			DescPT:       "Um homem olhando para seis copos com uma menina. Nostalgia, felicidade do passado, inocência.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/cp06.jpg",
		},
		{
			ID:           "cp07",
			NamePT:       "Sete de Copas",
			NameShort:    "cp07",
			Type:         "minor",
			Suit:         "cups",
			ValueInt:     7,
			MeaningUpPT:  "Fantasia, imaginação, ilusão, sonho, ambição, escolha, desejo, irrealismo.",
			MeaningRevPT: "Desilusão, fantasia quebrada, ambição frustrada, pesadelo, realidade implacável.",
			DescPT:       "Um cavaleiro contemplando sete copos flutuantes com um dragão. Fantasia, imaginação, ilusão, sonho.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/cp07.jpg",
		},
		{
			ID:           "cp08",
			NamePT:       "Oito de Copas",
			NameShort:    "cp08",
			Type:         "minor",
			Suit:         "cups",
			ValueInt:     8,
			MeaningUpPT:  "Busca, renovação, saída, transcendência, introspecção, abandono do passado, crescimento emocional.",
			MeaningRevPT: "Angústia, busca frustrada, retorno, ralento, perda de direção, instabilidade.",
			DescPT:       "Uma mulher deixando oito copos para entrar em uma cabana na floresta. Busca, renovação, saída.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/cp08.jpg",
		},
		{
			ID:           "cp09",
			NamePT:       "Nove de Copas",
			NameShort:    "cp09",
			Type:         "minor",
			Suit:         "cups",
			ValueInt:     9,
			MeaningUpPT:  "Desire, realização, abundância emocional, felicidade, contentamento, luxurious, gratidão, amor pleno.",
			MeaningRevPT: "Insatisfação, solidão, desejo inatingível, frustração, perda emocional, pessimismo.",
			DescPT:       "Uma mulher cercada por nove copos com um servente. Desejo realizado, abundância emocional, felicidade.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/cp09.jpg",
		},
		{
			ID:           "cp10",
			NamePT:       "Dez de Copas",
			NameShort:    "cp10",
			Type:         "minor",
			Suit:         "cups",
			ValueInt:     10,
			MeaningUpPT:  "Harmonia familiar, amor pleno, união, alegria doméstica, felicidade, ancestors, lares, contentamento.",
			MeaningRevPT: "Família problemática, perda de harmonia, desunião, conflito doméstico, infelicidade.",
			DescPT:       "Uma família debruçada em um muro de dez copos. Harmonia familiar, amor pleno, união.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/cp10.jpg",
		},
		// Copas — Cavaliere (Page)
		{
			ID:           "cpkn",
			NamePT:       "Príncipe de Copas",
			NameShort:    "cpkn",
			Type:         "minor",
			Suit:         "cups",
			ValueInt:     0,
			MeaningUpPT:  "Mensagem emocional, sensibilidade, jovem maduro, criatividade, comunicação simpática, intuição jovem.",
			MeaningRevPT: "Mensagem emocional falha, sensibilidade excessiva, fragilidade, comunicação emocional confusa.",
			DescPT:       "Um jovem cavaleiro com um barco à beira-mar. Mensagem emocional, sensibilidade, intuição jovem.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/cpkn.jpg",
		},
		// Copas — Rei
		{
			ID:           "cprg",
			NamePT:       "Rei de Copas",
			NameShort:    "cprg",
			Type:         "minor",
			Suit:         "cups",
			ValueInt:     0,
			MeaningUpPT:  "Emocionalmente maduro, empático, compassivo, confiante, intuído, generoso, cheio de vida.",
			MeaningRevPT: "Manipulador emocional, egoísta, frio, indiferente, instável emocionalmente, nemótico.",
			DescPT:       "Um rei sentado com coppas, com uma serpente em sua mão. Emocionalmente maduro, empático, compassivo.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/cprg.jpg",
		},
		// Copas — Rainha
		{
			ID:           "cprq",
			NamePT:       "Rainha de Copas",
			NameShort:    "cprq",
			Type:         "minor",
			Suit:         "cups",
			ValueInt:     0,
			MeaningUpPT:  "Intuitiva, compasionável, amorosca, atenta, calma, maternal, madura emocionalmente, acolhedora.",
			MeaningRevPT: "Manipuladora, excessivamente sentimental, possessiva, dramática, vadia emocionalmente.",
			DescPT:       "Uma rainha sentada com coppas, um cão, rodeada por flores. Intuitiva, compasionável, amorosca, calma.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/cprq.jpg",
		},
		// ---- ESPADAS (Swords) - Intelecto, conflito, verdades ----
		{
			ID:           "sp01",
			NamePT:       "As de Espadas",
			NameShort:    "sp01",
			Type:         "minor",
			Suit:         "swords",
			ValueInt:     1,
			MeaningUpPT:  "Claridade mental, verdade, insight, revelação, poder da inteligência, decisão, conquista.",
			MeaningRevPT: "Pensamento confuso, ilusão mental, falta de clareza, ingenuidade, fraqueza intelectual.",
			DescPT:       "Uma mão entre nuvens segurando uma espada com uma rosória. Claridade mental, verdade, insight.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/sp01.jpg",
		},
		{
			ID:           "sp02",
			NamePT:       "Dois de Espadas",
			NameShort:    "sp02",
			Type:         "minor",
			Suit:         "swords",
			ValueInt:     2,
			MeaningUpPT:  "Decisão difícil, equilíbrio, escassez de opções, paralisia, tensão, escolha entre o mal e o pior.",
			MeaningRevPT: "Vitória pela diplomacia, decisão tomada, resolução de conflito, neutralidade, nível heads.",
			DescPT:       "Uma figura cega com duas espadas cruzadas, com um mar azul. Decisão difícil, equilíbrio, tensão.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/sp02.jpg",
		},
		{
			ID:           "sp03",
			NamePT:       "Três de Espadas",
			NameShort:    "sp03",
			Type:         "minor",
			Suit:         "swords",
			ValueInt:     3,
			MeaningUpPT:  "Dor, tristeza, separação, luto, ferimento emocional, ruptura, perda, sofrimento.",
			MeaningRevPT: "Recuperação, cura, superação de dor, aceitação, fim da tristeza, reconciliação.",
			DescPT:       "Três espadas espetadas em um coração, com nuvens e chuva. Dor, tristeza, separação, luto.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/sp03.jpg",
		},
		{
			ID:           "sp04",
			NamePT:       "Quatro de Espadas",
			NameShort:    "sp04",
			Type:         "minor",
			Suit:         "swords",
			ValueInt:     4,
			MeaningUpPT:  "Repouso, quietude, meditação, recuperação, paz mental, férias, isenção de conflitos.",
			MeaningRevPT: "Início de nova ação, atividade mental, retorno à vida, ansiedade, agitação.",
			DescPT:       "Uma figura de dressed de bispo com uma cruz em uma igreja, com três espadas no chão. Repouso, quietude, meditação.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/sp04.jpg",
		},
		{
			ID:           "sp05",
			NamePT:       "Cinco de Espadas",
			NameShort:    "sp05",
			Type:         "minor",
			Suit:         "swords",
			ValueInt:     5,
			MeaningUpPT:  "Conflito, derrota, rivalidade, humilhação, injustiça, medo, inveja, ataque.",
			MeaningRevPT: "Vitória, sucesso, reconciliação, superação, paz, libertação da rivalidade.",
			DescPT:       "Três cavaleiros com espadas, um fugindo com uma bandeira murcha. Conflito, derrota, rivalidade, humilhação.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/sp05.jpg",
		},
		{
			ID:           "sp06",
			NamePT:       "Seis de Espadas",
			NameShort:    "sp06",
			Type:         "minor",
			Suit:         "swords",
			ValueInt:     6,
			MeaningUpPT:  "Transição, superação, mudança, viagem, abertura mental, passagem para o lado mais leve.",
			MeaningRevPT: "Imobilidade, resistência à mudança, estagnação, rejeição da transição, recalque.",
			DescPT:       "Um barco com pessoas viajando entre montanhas, com espadas cruzadas. Transição, superação, mudança.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/sp06.jpg",
		},
		{
			ID:           "sp07",
			NamePT:       "Sete de Espadas",
			NameShort:    "sp07",
			Type:         "minor",
			Suit:         "swords",
			ValueInt:     7,
			MeaningUpPT:  "Fraude, traição, deserção, estratégia, astúcia, invasão, medo, combate defensivo.",
			MeaningRevPT: "Competência, estratégia bem-sucedida, vitória intelectual, honra, derrota do invasor.",
			DescPT:       "Um homem pegando sete espadas enquanto o exército foge. Fraude, traição, estratégia, astúcia.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/sp07.jpg",
		},
		{
			ID:           "sp08",
			NamePT:       "Oito de Espadas",
			NameShort:    "sp08",
			Type:         "minor",
			Suit:         "swords",
			ValueInt:     8,
			MeaningUpPT:  "Limitação, restrição, crise mental, ansiedade, experiência desagradável, autoimposição.",
			MeaningRevPT: "Libertação gradual, saída de crise, superação, aceitação da realidade externa.",
			DescPT:       "Uma mulher amarrada com oito espadas, com um palhaço e um cubo. Limitação, restrição, ansiedade.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/sp08.jpg",
		},
		{
			ID:           "sp09",
			NamePT:       "Nove de Espadas",
			NameShort:    "sp09",
			Type:         "minor",
			Suit:         "swords",
			ValueInt:     9,
			MeaningUpPT:  "Ansiedade, temor, nightmare, sofrimento mental, tortura, culpa, preocupação excessiva.",
			MeaningRevPT: "Superação do medo, realização, paz interior, fim da ansiedade, libertação mental.",
			DescPT:       "Um homem deitado em uma cama com nove espadas na parede, olhando para um dragão. Ansiedade, temor, nightmare.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/sp09.jpg",
		},
		{
			ID:           "sp10",
			NamePT:       "Dez de Espadas",
			NameShort:    "sp10",
			Type:         "minor",
			Suit:         "swords",
			ValueInt:     10,
			MeaningUpPT:  "Fim, crise, desastre, agonia, fracasso, culpa, morte do pensamento, desespero.",
			MeaningRevPT: "Recuperação, início de nova fase, aceitação do fim, libertação do sofrimento.",
			DescPT:       "Um corpo com dez espadas no peito, olhando para o céu. Fim, crise, desastre, agonia.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/sp10.jpg",
		},
		// Espadas — Cavaliere (Page)
		{
			ID:           "spkn",
			NamePT:       "Príncipe de Espadas",
			NameShort:    "spkn",
			Type:         "minor",
			Suit:         "swords",
			ValueInt:     0,
			MeaningUpPT:  "Mensageiro intelectual, jovem ativo, comunicação, inquietação, investigação, iniciativa mental.",
			MeaningRevPT: "Mensagem confusa, inquietação mal direcionada, agitação, comunicação tardia, insegurança intelectual.",
			DescPT:       "Um jovem cavaleiro com uma espada. Mensageiro intelectual, jovem ativo, comunicação.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/spkn.jpg",
		},
		// Espadas — Rei
		{
			ID:           "sprg",
			NamePT:       "Rei de Espadas",
			NameShort:    "sprg",
			Type:         "minor",
			Suit:         "swords",
			ValueInt:     0,
			MeaningUpPT:  "Intelecto claro, justiça, autoridade mental, controle, honra, lógica, decisão firme.",
			MeaningRevPT: "Controlador, frieza, crueldade, egocentrismo, ambição desmedida, falta de empatia.",
			DescPT:       "Um rei sentado com espadas, olhos penetrantes. Intelecto claro, justiça, autoridade mental.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/sprg.jpg",
		},
		// Espadas — Rainha
		{
			ID:           "sprq",
			NamePT:       "Rainha de Espadas",
			NameShort:    "sprq",
			Type:         "minor",
			Suit:         "swords",
			ValueInt:     0,
			MeaningUpPT:  "Inteligência lúcida, independência, justiça, compreensão, clareza, atividade mental, coragem.",
			MeaningRevPT: "Manipulação, desconfiança excessiva, crueldade, frieza emocional, cinismo, inveja.",
			DescPT:       "Uma rainha sentada com espadas, um pássaro na mão. Inteligência lúcida, independência, justiça.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/sprq.jpg",
		},
		// ---- OU ROS (Pentacles) - Material, trabalho, prosperidade ----
		{
			ID:           "ou01",
			NamePT:       "As de Ouros",
			NameShort:    "ou01",
			Type:         "minor",
			Suit:         "pentacles",
			ValueInt:     1,
			MeaningUpPT:  "Novo início material, riqueza, oportunidade, prosperidade, sucesso, investimento, abundância nascente.",
			MeaningRevPT: "Perda financeira, mau investimento, estagnação, insucesso material, barreiras econômicas.",
			DescPT:       "Uma mão celeste derramando moedas de ouro. Novo início material, riqueza, oportunidade.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ou01.jpg",
		},
		{
			ID:           "ou02",
			NamePT:       "Dois de Ouros",
			NameShort:    "ou02",
			Type:         "minor",
			Suit:         "pentacles",
			ValueInt:     2,
			MeaningUpPT:  "Escolha financeira, dualidade material, equilíbrio entre trabalho e lazer, mudança de carreira.",
			MeaningRevPT: "Instabilidade, indecisão em questões de dinheiro, confusão no trabalho, desequilíbrio financeiro.",
			DescPT:       "Uma mulher segurando duas granadas cruzadas com seu vestido puxado. Escolha entre dois caminhos materiais.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ou02.jpg",
		},
		// ---- ESPADAS (Swords) - Intelecto, conflito, verdades ----
		// Espadas — Cavaliere (Page)
		// Espadas — Rei
		// Espadas — Rainha
		// ---- OU ROS (Pentacles) - Material, trabalho, prosperidade ----
		{
			ID:           "ou03",
			NamePT:       "Três de Ouros",
			NameShort:    "ou03",
			Type:         "minor",
			Suit:         "pentacles",
			ValueInt:     3,
			MeaningUpPT:  "Trabalho árduo, aprendizado técnico, construção, mérito, profissão, domínio, perseverança.",
			MeaningRevPT: "Falta de disciplina, trabalho incompleto, aprendizado interrompido, preguiça, negligência.",
			DescPT:       "Um homem trabalhando com granadas, com uma equipe. Trabalho árduo, aprendizado técnico, construção.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ou03.jpg",
		},
		{
			ID:           "ou04",
			NamePT:       "Quatro de Ouros",
			NameShort:    "ou04",
			Type:         "minor",
			Suit:         "pentacles",
			ValueInt:     4,
			MeaningUpPT:  "Estabilidade financeira, planejamento, segurança material, herança, abundância, acumulação.",
			MeaningRevPT: "Avareza, perda de oportunidades, medo de gastos, riqueza mal administrada, estagnação.",
			DescPT:       "Um homem contemplando quatro granadas com um saco de moedas. Estabilidade financeira, planejamento.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ou04.jpg",
		},
		{
			ID:           "ou05",
			NamePT:       "Cinco de Ouros",
			NameShort:    "ou05",
			Type:         "minor",
			Suit:         "pentacles",
			ValueInt:     5,
			MeaningUpPT:  "Crise financeira, perda material, miséria, dedução, necessidade, falta de recursos.",
			MeaningRevPT: "Recuperação material, auxílio financeiro, possibilidade de empréstimo, recursos vindouros.",
			DescPT:       "Um homem pobre de chapéu vendido fora de uma igreja com cinco granadas. Crise financeira, perda material.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ou05.jpg",
		},
		{
			ID:           "ou06",
			NamePT:       "Seis de Ouros",
			NameShort:    "ou06",
			Type:         "minor",
			Suit:         "pentacles",
			ValueInt:     6,
			MeaningUpPT:  "Generosidade, caridade, partilha, tributação, bem-estar financeiro, benevolência, prosperidade.",
			MeaningRevPT: "Ganância, avareza, desequilíbrio financeiro, perda por falta de generosidade, egoísmo.",
			DescPT:       "Um homem dando granada ao pobre, com um anel ao redor do dedo. Generosidade, caridade, partilha.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ou06.jpg",
		},
		{
			ID:           "ou07",
			NamePT:       "Sete de Ouros",
			NameShort:    "ou07",
			Type:         "minor",
			Suit:         "pentacles",
			ValueInt:     7,
			MeaningUpPT:  "Trabalho árduo, aprendizado técnico, disciplina, persistência, método, estudo, mérito.",
			MeaningRevPT: "Preguiça, fracasso, má direção, perda por negligência, falta de método.",
			DescPT:       "Um aprendiz trabalhando em granadas com as mãos. Trabalho árduo, aprendizagem técnica, disciplina.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ou07.jpg",
		},
		{
			ID:           "ou08",
			NamePT:       "Oito de Ouros",
			NameShort:    "ou08",
			Type:         "minor",
			Suit:         "pentacles",
			ValueInt:     8,
			MeaningUpPT:  "Aprendizado, trabalho árduo, desenvolvimento técnico, domínio de habilidade, perseverança, ofício.",
			MeaningRevPT: "Falta de disciplina, educação insuficiente, fuga do trabalho, incompetência persistente.",
			DescPT:       "Um artesão trabalhando com onze granadas. Aprendiz, trabalho manual, domínio de ofício.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ou08.jpg",
		},
		{
			ID:           "ou09",
			NamePT:       "Nove de Ouros",
			NameShort:    "ou09",
			Type:         "minor",
			Suit:         "pentacles",
			ValueInt:     9,
			MeaningUpPT:  "Sucesso consolidado, riqueza, bens fruitíferos, realização do trabalho, conforto, posse de bens.",
			MeaningRevPT: "Falha no planejamento, energia gasta em duplo, perda material recuperada, riqueza descartada.",
			DescPT:       "Uma mulher com nove granadas ao redor de um jardim. Frutos, riqueza estável, resultado do trabalho.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ou09.jpg",
		},
		{
			ID:           "ou10",
			NamePT:       "Dez de Ouros",
			NameShort:    "ou10",
			Type:         "minor",
			Suit:         "pentacles",
			ValueInt:     10,
			MeaningUpPT:  "Bem-estar material, sucessos, herança, segurança familiar, abundância consolidada, riqueza passada.",
			MeaningRevPT: "Perda de bens, objeções no mercado, ambiente familiar problemático, gastos excessivos, falência.",
			DescPT:       "Um homem e uma mulher com dez granadas, filhos ao redor, pedra de conforto. Sucesso total, paz familiar.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ou10.jpg",
		},
		// Ouros — Cavaliere (Page)
		{
			ID:           "oukn",
			NamePT:       "Príncipe de Ouros",
			NameShort:    "oukn",
			Type:         "minor",
			Suit:         "pentacles",
			ValueInt:     0,
			MeaningUpPT:  "Jovem trabalhador, empregado, empreendedor jovem, planejamento financeiro, consciência prática.",
			MeaningRevPT:  "Jovem infrutíferas, trabalhador descuidado, indevêdrio, perda por negligência.",
			DescPT:       "Um jovem cavaleiro com um poodle, cavalgando com uma granada ao fundo. Jovem aplicado.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/oukn.jpg",
		},
		// Ouros — Rei
		{
			ID:           "ourg",
			NamePT:       "Rei de Ouros",
			NameShort:    "ourg",
			Type:         "minor",
			Suit:         "pentacles",
			ValueInt:     0,
			MeaningUpPT:  "Homem de negócios, governante, controlador financeiro, riqueza, estabilidade, excelência.",
			MeaningRevPT: "Avareza, envolvimento em esquemas ilícitos, infortúnio material grave, avareza extrema.",
			DescPT:       "Um rei com pesadas vestes, granada no peito, duas granadas à frente. O homem de autoridade e riqueza.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ourg.jpg",
		},
		// Ouros — Rainha
		{
			ID:           "ourq",
			NamePT:       "Rainha de Ouros",
			NameShort:    "ourq",
			Type:         "minor",
			Suit:         "pentacles",
			ValueInt:     0,
			MeaningUpPT:  "Mulher prática, administrativa, consciência financeira, confortável, sólida, empresária.",
			MeaningRevPT: "Mulher avara, egoísta, descuidada do lar, acumulação por medo, ganância.",
			DescPT:       "Uma rainha sentada com granadas, vestidos bordados, um cão e um gato perto. Mulher de conforto e administração.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/ourq.jpg",
		},
		// ---- PAUS (Wands) - Ação, criatividade, energia, expansão ----
		{
			ID:           "pk01",
			NamePT:       "As de Paus",
			NameShort:    "pk01",
			Type:         "minor",
			Suit:         "wands",
			ValueInt:     1,
			MeaningUpPT:  "Inspiração, criatividade, iniciativa, energia vital, início de projeto, impulso, ação.",
			MeaningRevPT: "Energia bloqueada, iniciativa falha, mal-estar, criação frustrada, desalentamento.",
			DescPT:       "Uma mão celeste derramando uma vara de pote — mesmo símbolo do Mago. Início de projeto, impulso.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/pk01.jpg",
		},
		{
			ID:           "pk02",
			NamePT:       "Dois de Paus",
			NameShort:    "pk02",
			Type:         "minor",
			Suit:         "wands",
			ValueInt:     2,
			MeaningUpPT:  "Decisão de longo prazo, análise, plano de vida, escolha de futuro, equilíbrio entre visões.",
			MeaningRevPT: "Indecisão prolongada, perda de tempo, falta de conclusão, vida estagnada.",
			DescPT:       "Uma mulher em frente ao mar com dois varas cruzados. Decisão de longo prazo, análise.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/pk02.jpg",
		},
		{
			ID:           "pk03",
			NamePT:       "Três de Paus",
			NameShort:    "pk03",
			Type:         "minor",
			Suit:         "wands",
			ValueInt:     3,
			MeaningUpPT:  "Crescimento, expansão, trabalho em equipe, sucesso na carreira, progresso, liderança.",
			MeaningRevPT: "Falta de arquitetura, impaciência, excesso de expansão, projeto descuidado.",
			DescPT:       "Três varas penduradas num poste, com um homem olhando o horizonte. Construção, planejamento.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/pk03.jpg",
		},
		{
			ID:           "pk04",
			NamePT:       "Quatro de Paus",
			NameShort:    "pk04",
			Type:         "minor",
			Suit:         "wands",
			ValueInt:     4,
			MeaningUpPT:  "Estabilidade, conforto, festas domésticas, descanso, prosperidade pós-esforço, união de família.",
			MeaningRevPT: "Vaidade, pedantismo, conforto que estagna, reação excessiva, festa fake.",
			DescPT:       "Quatro varas representando as estações. Uma mesa com comida ao fundo. Celebração, conforto.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/pk04.jpg",
		},
		{
			ID:           "pk05",
			NamePT:       "Cinco de Paus",
			NameShort:    "pk05",
			Type:         "minor",
			Suit:         "wands",
			ValueInt:     5,
			MeaningUpPT:  "Conflito, rivalidade, luta, oposição, competição, guerra de ego, ruína do engano.",
			MeaningRevPT: "Vitória, superação, recuo do inimigo, sucesso de xadrez, conflito superado.",
			DescPT:       "Cinco homens com varas — luta, rivalidade. O homem aljofrado venceu três. Conflito entre poderosos.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/pk05.jpg",
		},
		{
			ID:           "pk06",
			NamePT:       "Seis de Paus",
			NameShort:    "pk06",
			Type:         "minor",
			Suit:         "wands",
			ValueInt:     6,
			MeaningUpPT:  "Vitória, sucesso, superação de obstáculos, jornada, competição, auto-confiança.",
			MeaningRevPT: "Fracasso, derrota inesperada, demora, frustração, derrota por medo.",
			DescPT:       "Cavalheiro a cavalo, com um servo, apresentando bandeira de vitória. Vitória, sucesso, auto-confiança.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/pk06.jpg",
		},
		{
			ID:           "pk07",
			NamePT:       "Sete de Paus",
			NameShort:    "pk07",
			Type:         "minor",
			Suit:         "wands",
			ValueInt:     7,
			MeaningUpPT:  "Desafio, defesa, esforço, campanha, possível vitória, triunfo do trabalho, ação defensiva.",
			MeaningRevPT: "Derrota inesperada, desastre em campanha, recuo, inabilities para defender, abandono.",
			DescPT:       "Um homem em alta posição com varas. Desafio, defesa, campanha, esforço.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/pk07.jpg",
		},
		{
			ID:           "pk08",
			NamePT:       "Oito de Paus",
			NameShort:    "pk08",
			Type:         "minor",
			Suit:         "wands",
			ValueInt:     8,
			MeaningUpPT:  "Viagens, mudanças rápidas, ação impulsiva, movimento, caminho traçado, ir e vir.",
			MeaningRevPT: "Viagens mal sucedidas, interrupções, fuga inútil, maus caminhos, impaciência desnecessária.",
			DescPT:       "Oito varas se movendo por vento. Viagens, mudanças, rápida ação, impulsividade.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/pk08.jpg",
		},
		{
			ID:           "pk09",
			NamePT:       "Nove de Paus",
			NameShort:    "pk09",
			Type:         "minor",
			Suit:         "wands",
			ValueInt:     9,
			MeaningUpPT:  "Desgaste, exaustão, frustração, obstáculos, recuperação lenta, empreendimentos frustrados, ansiedade.",
			MeaningRevPT: "Coisas superadas, os inimigos são poucos, vitória position, exaustão superada.",
			DescPT:       "Nove varas plantadas no chão, um homem com vara enfrentando um deles. Desgaste, exaustão.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/pk09.jpg",
		},
		{
			ID:           "pk10",
			NamePT:       "Dez de Paus",
			NameShort:    "pk10",
			Type:         "minor",
			Suit:         "wands",
			ValueInt:     10,
			MeaningUpPT:  "Carga pesada, responsabilidade excessiva, sobrecarga, cansaço final, grandes esforços com resultado.",
			MeaningRevPT: "Libertação parcial, desgaste menos grave, trabalho compartilhado, fuga de responsabilidades.",
			DescPT:       "Um homem carregando dez varas sobre os ombros, quase acabando. A carga que pesa.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/pk10.jpg",
		},
		// Paus — Cavaliere (Page)
		{
			ID:           "pknk",
			NamePT:       "Príncipe de Paus",
			NameShort:    "pknk",
			Type:         "minor",
			Suit:         "wands",
			ValueInt:     0,
			MeaningUpPT:  "Jovem aventureiro, comerciante, criador, empreendedor, comunicador, produtivo, entusiasmado.",
			MeaningRevPT:  "Jovem descompassado, aventureiro perigoso, inapto, comunicações falhas.",
			DescPT:       "Um jovem cavaleiro em um cavalo branco com varas ao fundo. Viagens novidade, empreendedorismo jovem.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/pknk.jpg",
		},
		// Paus — Rei
		{
			ID:           "pkrk",
			NamePT:       "Rei de Paus",
			NameShort:    "pkrk",
			Type:         "minor",
			Suit:         "wands",
			ValueInt:     0,
			MeaningUpPT:  "Homem de ação, líder, empresário, comerciante, inventor, dinamismo, executivo em movimento.",
			MeaningRevPT:  "Líder incompetente, empresário fracassado, insegurança, inaptidão profissional, tirania ineficaz.",
			DescPT:       "Rei sentado com varas, olhos penetrantes, vestes vermelhas e pretas. Energia, ação, poder executivo.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/pkrk.jpg",
		},
		// Paus — Rainha
		{
			ID:           "pkrq",
			NamePT:       "Rainha de Paus",
			NameShort:    "pkrq",
			Type:         "minor",
			Suit:         "wands",
			ValueInt:     0,
			MeaningUpPT:  "Mulher independente, criativa, entusiasta, comunicadora, empresária, organização sem rigidez.",
			MeaningRevPT:  "Mulher complicada, egoísta, dominadora, arrogante, exigente, mulher de ações mal direcionadas.",
			DescPT:       "Rainha sentada com varas, cabelos ao vento. Mulher de energia, criatividade e ação.",
			ImageURL:     "https://cdn.jsdelivr.net/gh/jamile-dev/lets-tarot@v0.1.0/cards/pkrq.jpg",
		},
	}

	// Ensure the correct number of cards
	if len(cards) != 74 {
		panic(fmt.Sprintf("Expected 74 cards (TaionWC RWS deck), got %d", len(cards)))
	}

	return cards
}

// CardIDs returns all 78 card IDs as a map for quick lookup
func CardIDs() map[string]bool {
	ids := make(map[string]bool)
	for _, c := range DefaultCards() {
		ids[c.ID] = true
	}
	return ids
}

// GenerateCardID returns a deterministic ID for a card based on suit and value
func GenerateCardID(suit, value string) string {
	switch suit {
	case "major":
		return "ar" + value
	case "cups":
		if value == "page" {
			return "cpkn"
		}
		if value == "king" {
			return "cprg"
		}
		if value == "queen" {
			return "cprq"
		}
		return "cu" + value
	case "swords":
		if value == "page" {
			return "spkn"
		}
		if value == "king" {
			return "sprg"
		}
		if value == "queen" {
			return "sprq"
		}
		return "es" + value
	case "pentacles":
		if value == "page" {
			return "oukn"
		}
		if value == "king" {
			return "ourg"
		}
		if value == "queen" {
			return "ourq"
		}
		return "ou" + value
	case "wands":
		if value == "page" {
			return "pknk"
		}
		if value == "king" {
			return "pkrk"
		}
		if value == "queen" {
			return "pkrq"
		}
		return "pk" + value
	default:
		return uuid.New().String()
	}
}
